package olshop_billing_systems;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Random;
import javax.swing.JOptionPane;

public class Frame_Olshop_Billing extends javax.swing.JFrame {
    static double harga,total,jumlah;
    static float price, cost;
    static String kode,nama,merk;
    static int nomor, stok, a;
    static String daftar;
    static Random rnd = new Random();
    static Simpan simpan = new Simpan();

    public Frame_Olshop_Billing() {
        initComponents();
        tblHasil.setModel(simpan.getTabel());

        cmbKode.addItem("SPT001");
        cmbKode.addItem("SPT002");
        cmbKode.addItem("SPT003");
        cmbKode.addItem("SPT004");
        cmbKode.addItem("SPT005");
        cmbKode.addItem("SPT006");
        cmbKode.addItem("SPT007");
        cmbKode.addItem("SPT008");
        cmbKode.addItem("SPT009");
        cmbKode.addItem("SPT010");
        cmbKode.addItem("SPT011");
        cmbKode.addItem("SPT012");
        cmbKode.addItem("SPT013");
        cmbKode.addItem("SPT014");
        cmbKode.addItem("SPT015");

        cmbColor.addItem("Banana");
        cmbColor.addItem("Beige");
        cmbColor.addItem("Black");
        cmbColor.addItem("Blue");
        cmbColor.addItem("Blue-Green");
        cmbColor.addItem("Bone");
        cmbColor.addItem("Brown");
        cmbColor.addItem("Charcoal");
        cmbColor.addItem("Coral");
        cmbColor.addItem("Cream");
        cmbColor.addItem("Dark Brown");
        cmbColor.addItem("Dark Gray");
        cmbColor.addItem("Gray");
        cmbColor.addItem("Green");
        cmbColor.addItem("Light Blue");
        cmbColor.addItem("Light Gray");
        cmbColor.addItem("Light Brown");
        cmbColor.addItem("Mustrad");
        cmbColor.addItem("Maroon");
        cmbColor.addItem("Mauve");
        cmbColor.addItem("Navy");
        cmbColor.addItem("Orange");
        cmbColor.addItem("Pink");
        cmbColor.addItem("Peach");
        cmbColor.addItem("Purple");
        cmbColor.addItem("Plum");
        cmbColor.addItem("Periwinkle");
        cmbColor.addItem("Red");
        cmbColor.addItem("Sea Foam");
        cmbColor.addItem("Teal");
        cmbColor.addItem("Turquoise");
        cmbColor.addItem("Violet");
        cmbColor.addItem("White");
        cmbColor.addItem("yellow");

        cmbSize.addItem("27");
        cmbSize.addItem("28");
        cmbSize.addItem("29");
        cmbSize.addItem("30");
        cmbSize.addItem("31");
        cmbSize.addItem("32");
        cmbSize.addItem("33");
        cmbSize.addItem("34");
        cmbSize.addItem("35");
        cmbSize.addItem("36");
        cmbSize.addItem("37");
        cmbSize.addItem("38");
        cmbSize.addItem("39");
        cmbSize.addItem("40");
        cmbSize.addItem("41");
        cmbSize.addItem("42");
        cmbSize.addItem("43");
        cmbSize.addItem("44");
        cmbSize.addItem("45");
        cmbSize.addItem("46");
        cmbSize.addItem("47");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbKode = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodeBeli = new javax.swing.JTextField();
        TotalHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jbDaftar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        cmbColor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        cmbSize = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 30)); // NOI18N
        jLabel1.setText("Sistem Penjualan Sepatu Online Shop");
        jLabel1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cmbKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKodeActionPerformed(evt);
            }
        });

        txtJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Pembelian");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Harga Total");

        kodeBeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodeBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeBeliActionPerformed(evt);
            }
        });

        TotalHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(kodeBeli))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Kode Barang");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ukuran Sepatu");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Warna Sepatu");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Jumlah Pembelian");

        jbDaftar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbDaftar.setText("!");
        jbDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDaftarActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        cmbColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColorActionPerformed(evt);
            }
        });

        tblHasil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Sepatu", "Merk Sepatu", "Ukuran Sepatu", "Warna", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblHasil);

        cmbSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbKode, 0, 160, Short.MAX_VALUE)
                                    .addComponent(cmbColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumlah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDaftar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBeli)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnBeli))
                        .addGap(39, 39, 39))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        String[]data = new String[7];
        data[0] = (String) cmbKode.getSelectedItem();
        kode =(String)cmbKode.getSelectedItem();

        data[3] = (String)cmbSize.getSelectedItem();
        data[4] = (String)cmbColor.getSelectedItem();
        try{
            data[5] = txtJumlah.getText();
            jumlah=Float.parseFloat(txtJumlah.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "PERIKSA JUMLAH PEMESANAN ANDA!!!\n" + e);
        }
        switch (kode) {
            case "SPT001":
                nama= "Adidas F5,9 Original";
                merk = "Adidas";
                harga = 259000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT002":
                nama = "Predito Lz In Futsal Shoes";
                merk = "Adidas";
                harga = 215000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT003":
                nama = "M Attitude Logo 3";
                merk = "Adidas";
                harga = 1100000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT004":
                nama = "Zx";
                merk = "Adidas";
                harga = 210000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT005":
                nama = "Zx Vietnam";
                merk = "Adidas";
                harga = 228000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT006":
                nama = "Elastico Pro Original";
                merk = "Nike";
                harga = 699000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT007":
                nama = "Hyperfuse Low Shoes";
                merk = "Nike";
                harga = 1180000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT008":
                nama = "Vrona Slip On Shoes";
                merk = "Nike";
                harga = 730000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT009":
                nama = "Era Croc Leather";
                merk = "Vans";
                harga = 1249000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT010":
                nama = "Classic Classic Sneakers ";
                merk = "Vans";
                harga = 949000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT011":
                nama = "U Authentic Plaid";
                merk = "Vans";
                harga = 899000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT012":
                nama = "All Star Quantum";
                merk = "Convers";
                harga = 999000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT013":
                nama = "Chuck Taylor All Star";
                merk = "Convers";
                harga = 1199000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT014":
                nama = "Chuck Taylor All Star II";
                merk = "Converse";
                harga = 1399000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            case "SPT015":
                nama = "Deck Star '70";
                merk = "Converse";
                harga = 1199000;
                price = (float) (harga*jumlah);
                data[1] = String.valueOf(nama);
                data[2] = String.valueOf(merk);
                data[6] = String.valueOf(price);
                break;
            default:
                break;
        }
        a += 1;
        simpan.getTabel().addRow(data);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jbDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDaftarActionPerformed

        FileInputStream finput=null;
        int data;
        //membuka file
        try{
            finput = new FileInputStream("/Users/pnjrmdn/Documents/Input.txt");
        }catch(IOException e){}
        //membaca data dari dalam file dan menpilkanya ke layar
        try{
            while((data = finput.read())!=-1){
                //ketika di tampikan data di konversi ketipe char
                System.out.print((char) data);
            }
        }catch(IOException e){}
        try{
             finput.close();
        }catch(IOException e){}
    }//GEN-LAST:event_jbDaftarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        simpan.getTabel().removeRow(tblHasil.getSelectedRow());
    }//GEN-LAST:event_btnHapusActionPerformed

    private void kodeBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeBeliActionPerformed
    }//GEN-LAST:event_kodeBeliActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        nomor = (int)(rnd.nextInt(100000)+1000);
        kodeBeli.setText("Za08bC"+nomor);

        for (int i = 0; i < a; i++) {
            cost = cost + price;}

        TotalHarga.setText("RP"+ Math.ceil(cost));
    }//GEN-LAST:event_btnBeliActionPerformed

    private void cmbKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKodeActionPerformed
    }//GEN-LAST:event_cmbKodeActionPerformed

    private void cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColorActionPerformed

    private void cmbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSizeActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed

    }//GEN-LAST:event_txtJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Olshop_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Olshop_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Olshop_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Olshop_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Olshop_Billing().setVisible(true);
            }
        });}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotalHarga;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbKode;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDaftar;
    private javax.swing.JTextField kodeBeli;
    private javax.swing.JTable tblHasil;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables

    private void setText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
